from typing import Dict
import re

class ExercisesParser:
    """
    parses exercises generated by task generator
    """

    def __init__():
        pass

    def parse(input: str) -> Dict[str, str]:
        """
        parses exercises generated by task generator

        Parameters:
        -----------
        input: str
            a string containing task definition, a generated text and generated exercises
        """

        contents_pattern = r'\[(.*?)\]'
        task_def_contents = re.findall(contents_pattern, input, re.DOTALL)

        exercises_text = task_def_contents[6]

        exercises_pattern = r'\[START\](.*?)\[END\]'
        exercises_raw_str = re.findall(exercises_pattern, input, re.DOTALL)

        for exercise in exercises_raw_str:
            content = re.findall(contents_pattern, exercise, re.DOTALL)
            



"""
[START]
Type: [single-choice]
Question: [Welche Städte besuchte der Erzähler in Italien?]
Answer options: [a) Rom, Florenz und Venedig b) Mailand, Rom und Florenz c) Rom, Venedig und Neapel d) Florenz, Venedig und Mailand]
Solution: [a) Rom, Florenz und Venedig]
[END]
"""



"""
[START]
Type: [gaps]
Question: [Füllen Sie die Lücken basierend auf dem Text]
Answer options: [1. In Florenz ging ich in die [Uffizien, Museen, Kirchen]. 2. In Venedig gefielen mir die [Kanäle, Straßen, Gebäude] und Brücken.]
Solution: [Uffizien, Kanäle]
[END]
"""

"""
[START]
Type: [open]
Question: [Warum war der Urlaub des Erzählers wunderbar? Nutzen Sie Details aus dem Text.]
Answer options: None
Solution: [Der Urlaub des Erzählers war wunderbar, weil er das Kolosseum und das Pantheon in Rom sah, viele schöne Kunstwerke in den Uffizien in Florenz bewunderte und die Kanäle und Brücken in Venedig genoss. Außerdem aß er jeden Tag leckeres italienisches Essen und hatte gutes Wetter.]
[END]
"""

