@startuml
!theme plain

() AnswerAPI
() LessonAPI
() ChatAPI

package "Agent Service" {
  [FlaskApp] --> AnswerAPI
  [FlaskApp] --> LessonAPI
  [FlaskApp] <--> [Agent]
  [FlaskApp] <--> [RAG]
  [FlaskApp] <--> [LessonMaster]
}

package "Curriculum Service" {
  () CurriculumAPI
  [LessonController] --> CurriculumAPI
  [LessonController] --> [LessonService]
  [LessonService] --> LessonAPI
}


package "API Gateway" {
  [ChatController] --> ChatAPI
  [ChatService] --> AnswerAPI
  [ChatService] --> CurriculumAPI
  [ChatService]
  [ChatController] --> [ChatService]
}


package "Client" {
  package "Presentation" {
    [Screens]
    [Widgets]
    [Blocs]
  }
  package "Domain" {
    [Entities] 
    [Entities] 
    [Repositories]
    [Use Cases]
  }
    package "Data" {
    [Models] 
    [Data Providers]  --> ChatAPI
    [Repositories Impl]
  }
  Domain <--> Presentation
  Domain <--> Data
}

database "MilvusVectorStore" {
  folder "LawLifeKnowledgeBase" {
 }
 folder "TrajectoryLibrary" {
 }
}

database "Curriculum" {
  folder "curriculum.json" {
 }

LessonService --> Curriculum
FlaskApp --> MilvusVectorStore
}

@enduml