@startuml

package frontend {
    package styles {
        package app_styles.dart {
            class AppStyles {
                +Color accentColor
                +Color sandColor
                +Color darkColor
                +TextStyle settingsOptionsTextStyle
                +TextStyle settingstextStyle
                +TextStyle mainMenuTitleTextStyle
                +TextStyle taskQuestionTextStyle
                +TextStyle taskOptionTextStyle
                +TextStyle messageTextStyle
                +TextStyle buttonTextStyle()
            }
        }
    }
    package utils {
        package l10n {
            package app_localization.dart {
                class AppLocalizations {
                    +Locale locale
                    +LocalizationsDelegate<AppLocalizations> delegate
                    -Map<String, String>? _localizedStrings
                    +AppLocalizations of()
                    +dynamic load()
                    +String translate()
                }

                class _AppLocalizationsDelegate {
                    +bool isSupported()
                    +dynamic load()
                    +bool shouldReload()
                }
            }
        }
        class MetadataUtils {
            +dynamic initUserId()
            +String generateMessageID()
        }
        class AudioUtils {
        -AudioPlayer _audioPlayer
        +String? audioFilePath
        +Duration maxDuration
        +Duration elapsedDuration
        +Stream<Duration> positionStream
        +dynamic prepareAudioFile()
        +dynamic playPauseAudio()
        +dynamic resetAudio()
        +void dispose()
        }
    }
    package data {
        package models {
            class MessageModel {
                +String text
                +String userID
                +String messageID
                +String role
                +DateTime timestamp
                +MessageType messageType
                +String audio
                +String video
                +String getText
                +String getUserID
                +String getMessageID
                +String getRole
                +DateTime getTimestamp
                +Map<String, dynamic> toJson()  
                        }

            class TaskModel {
                +TaskType type
                +String question
                +List<List<String>> answerOptions
                +List<String> solutions
                +int id
                +String lessonType
                +Map<String, dynamic> toJson()
            }
        }
        package data_providers {
            class ChatDataProvider {
                +String baseUrl
                +dynamic sendMessage()
                +dynamic sendImage()
                +dynamic fetchLesson()
                +dynamic fetchTasks()
            }
            class TaskDataProvider {
                +String baseUrl
                +dynamic submitUserAnswers()
            }
        }
        package repositories {
            class ChatRepositoryImpl {
                +ChatDataProvider chatDataProvider
                +dynamic sendMessage()
                +dynamic sendImage()
                +dynamic fetchLesson()
                +dynamic fetchTasks()
            }
            class TaskRepositoryImpl {
                +TaskDataProvider dataProvider
                +dynamic submitUserAnswers()
            }
        }
    }
    package domain {
        package repositories {
            interface ChatRepository {
                +dynamic sendMessage()
                +dynamic sendImage()
                +dynamic fetchLesson()
                +dynamic fetchTasks()
            }
            interface TaskRepository {
                +dynamic submitUserAnswers()
            }
        }
        package usecases {
            class SendMessage {
                +ChatRepository repository
                +dynamic call()
            }
            class SendImage {
                +ChatRepository repository
                +dynamic call()
            }
            class SubmitAnswers {
                +TaskRepository repository
                +dynamic call()
            }
            class FetchLesson {
                +ChatRepository repository
                +dynamic call()
            }
            class FetchTasks {
                +ChatRepository repository
                +dynamic call()
            }
        }
        package entities {
            class Message {
                +String text
                +String userID
                +String messageID
                +String role
                +DateTime timestamp
                +MessageType messageType
                +String audio
                +String video
            }
            class Task {
                +TaskType type
                +String question
                +List<List<String>> answerOptions
                +List<String> solutions
                +int id
                +String lessonType
                +List<String> userAnswers
                +bool completed
            }
            class TaskType {
                +int index
                +List<TaskType> values
                +TaskType multipleChoice
                +TaskType fillTheGaps
                +TaskType openQuestion
            }
            class MessageType {
                {static} +MessageType message
                {static} +MessageType reading
                {static} +MessageType listening
                {static} +MessageType grammar
                {static} +MessageType listeningVideo
            }
        }
    }
    package presentation {
        package blocs {
            class ChatBloc {
                +SendMessage sendMessage
                +SendImage sendImage
                +FetchLesson fetchLesson
                +FetchTasks fetchTasks
                +String userID
                +Map<String, List<Message>> chatMessages
                +Message getLessonOfferingMessage()
                +String getInitMessageGerman()
                +String getInitMessageLaw()
            }
            class LanguageBloc {
                -void _onLanguageChanged()
            }
            class TaskBloc {
                +SubmitAnswers submitAnswers
                +ChatBloc chatBloc
            }
        }
        package screens {
            class LawChatScreen {
                +String chatID
                +Widget build()
            }
            class GermanChatScreen {
                +String chatID
                +Widget build()
            }
            class SettingsScreen {
                +Widget build()
            }
            class TaskSequenceScreen {
                +List<Task> tasks
                +Widget build()
            }
            class MainMenuScreen {
                +Widget build()
            }
            class QuestionListScreen {
                +Widget build()
            }
        }
    }
}

@enduml