@startuml
left to right direction
actor User
actor System
rectangle "Welcome Screen" {
  usecase "Log in" as UC1a
  usecase "Create New Account" as UC1b
  usecase "First Time Login Guide" as UC1c
  usecase "Navigate Main Menu" as UC1d
}
rectangle "Chat with German Bot" {
  usecase "Send Message & Get Response" as UC2a
  usecase "Restore Message History" as UC2b
  usecase "Start New Lesson" as UC2c
  usecase "Automatic Translation" as UC2d
  usecase "Complete Tasks" as UC2e
  usecase "View Progress" as UC2f
  usecase "Update Learning State" as UC2g
}
rectangle "Persisting Message Data" {
  usecase "Save Message History" as UC3
}
rectangle "Chat with Recht und Alltag Bot" {
  usecase "Send Message & Get Response (Recht & Alltag)" as UC4a
}
User -- UC1a
User -- UC1b
User -- UC1c
User -- UC1d
User -- UC2a
User -- UC2c
User -- UC2d
User -- UC2e
User -- UC2f
User -- UC4a
UC2a -- UC3
UC2b -- UC3
UC4a -- UC3
System -- UC3
System -- UC2b
System --  UC2g
@enduml